[build]
target = "riscv32imc-unknown-none-elf"

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
]

[env]
ESP_LOG = "info"
LED_ORCHESTRA_WIFI_SSID = { value = "", force = false }
LED_ORCHESTRA_WIFI_PASSWORD = { value = "", force = false }
